### ISSUE TITLE
Error in algorithm?

### ISSUE THREAD

**Issue by pdb5627** [DanieleGioia/ScenarioReducer#1]
Hi! Thank you for sharing your work! It has been a good starting point for scenario reduction for a project I am working on. I think you may have an error in your algorithm. Referencing the Heitsch and Römisch paper, in each step i, it looks like the distance matrix should be updated according to the following rule:

```math
c^{[i]}_{ku} := \min \left\{ c^{[i-1]}_{ku}, c^{[i-1]}_{ku_{i-1}} \right\}, k, u \in J^{[i-1]}
```
I don't see that your code does this update. I plan to put together a pull request to address this.

**Comment by DanieleGioia** [comment]
Thank you for your contribution.
