### ISSUE TITLE
How to determine the initial_probs

### ISSUE THREAD

**Issue by 0wenwu** [DanieleGioia/ScenarioReducer#6]
are the `initial_probs` all type of time series data is initialized by  `(1/scenarios_num)*np.ones(scenarios_num)`
does the value of `initial_probs` affect the effect of reduction

**Comment by DanieleGioia** [comment]
The reduction algorithm transcends the technique of creating the initial distribution, and the choice of scenarios with uniform mass is only illustrative :).
