### ISSUE TITLE
How can I know the propability mass shipped from original scenarios to new senarios?

### ISSUE THREAD

**Issue by bmmddzgj** [DanieleGioia/ScenarioReducer#7]
I wanna know the amount of propability mass shipped from $\xi^i$ to $\zeta^j$, represented by $\pi_{ij}$, how can I get it.
I know the problem is as follows

![image](https://github.com/DanieleGioia/ScenarioReducer/assets/51513025/2aafba0a-0164-4b95-a3d7-6bf20a9d3704)
$$\begin{aligned}\min_{\pi\in\mathbb{R}_{+}^{n\times m}}&\sum_{i=1}^n\sum_{j=1}^m\pi_{ij}\|\xi^i-\zeta^j\|^2\\\text{subject to}&\sum_{j=1}^m\pi_{ij}=p_i,\quad\forall i\in[n],\\&\sum_{i=1}^n\pi_{ij}=q_j,\quad\forall j\in[m].\end{aligned}$$

Actually I want to use this method for clustering, and I wanna know the cluster of original scenarios.

**Comment by DanieleGioia** [comment]
Hi, 

The currently implemented scenario reducer is the (FF) Fast-Forward technique; it is a heuristic. The NP-hard transport problem you mentioned is not explicitly solved in this library.
The FF heuristic comes from the very famous paper:

Heitsch, Holger, and Werner Römisch. "Scenario reduction algorithms in stochastic programming." Computational optimization and applications 24 (2003): 187-206. 

I think the closest thing to the value you are looking for is within the redistribution part of the algorithm ( Eq.(10) in the article). In the library, there is a "redistribute_probs" function in the fast_forward.py script. Roughly speaking, the mass of erased scenarios is eventually given to the closest not erased one.
The idea is, in fact, somewhat closer to clustering :).

Additionally, if you want to implement other things, consider that the algorithm computes the distance matrix ( compute_distance_matrix function in fast_forward.py) between scenarios, if the current algorithm doesn't help you, at least you have somewhere to start from. 

I hope this will help,
Daniele.
